### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by cole-js** [krypto-i9/fixbit#6]
![Screenshot (142)](https://user-images.githubusercontent.com/56025451/101888313-fcbf7780-3bc3-11eb-840a-924c4dd3807a.png)

**Comment by krypto-i9** [comment]
Error is only arise in **Windows**. No problem in Linux.

**Comment by krypto-i9** [comment]
Routes.jsx changed to Router.jsx (No more confusing with routes.json and Routes.jsx)
